use_frameworks!

target 'Elliot' do
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SwiftyUserDefaults'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'KeychainAccess'
  pod 'Nuke', '~> 4.0'
  pod 'BRYXBanner'
  pod 'Presentr'
  pod 'PhoneNumberKit', '~> 1.2'

  # React Native Dependencies

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'DevSupport',
  ]
  
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization/' 
  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
end

# Explicitly set the Swift version for Swift pods 
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
